version: '3'

services:
  web:
    image: php:apache
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project_u
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "2000:8080"
