version: '3'

services:
  web:
    build: ../web
    ports:
      - "80:80"
    volumes:
      - ../web/public:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project_u
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 2000:8080
